apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-kube-descheduler-operator 
  namespace: descheduler-operator 
spec:
  channel: '4.8'
  name: cluster-kube-descheduler-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
