provider: local

projects:
  - num: 1
    basename: pod-affinity-s1-
    tuning: default
    ifexists: delete
    pods:
      - total: 130
      - num: 100
        image: docker.io/ocpqe/hello-pod
        basename: pod-affinity-security-in-s1
        file: /root/svt/openshift_scalability/content/pod-pod-affinity.json

  - num: 1
    basename: pod-anti-affinity-s1-
    tuning: default
    ifexists: delete
    pods:
      - total: 130
      - num: 100
        image: docker.io/ocpqe/hello-pod
        basename: pod-anti-affinity-security-in-s1
        file: /root/svt/openshift_scalability/content/pod-pod-anti-affinity.json


tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 50
        pause: 120
      ratelimit:
        delay: 0

