projects:
- basename: clusterproject
  ifexists: delete
  num: 75
  templates:
  - file: ../content/statefulset-pv-template.json
    num: 1
  tuning: default
quotas:
- name: default
tuningsets:
- name: default
  pods:
    rate_limit:
      delay: 250 ms
    stepping:
      pause: 10 s
      stepsize: 5
